configured local development environment using docker
mozilla/tantalus pull request #16
Opened 2019-04-11 16:51 UTC by kimberlythegeek

fixes #12 #8 

cleaned up the unused files a bit, configured docker for a local dev environment, updated the readme

2019-04-11 16:51 UTC, kimberlythegeek commented
Yes, this is a big, scary PR. a lot of artifacts were removed.

2019-04-11 16:52 UTC, kimberlythegeek commented
Yes, this is a big, scary PR. a lot of artifacts were removed.

2019-04-12 21:35 UTC, m8ttyB commented
Just wanted to give an update. I'm still chewing through the review. ty for your patience.

2019-04-12 22:28 UTC, m8ttyB requested changes
A few suggested changes for the readme

2019-04-12 22:28 UTC, m8ttyB commented on README.md
> +docker-compose build && docker-compose up
Nit: on the first run of `docker-compose up`, when a bughunter container has not yet been built, the build command happens automatically. `docker-compose build` only needs to be run if the `Dockerfile` referenced by the `docker-compose.yml` file has changed.

2019-04-23 17:57 UTC, m8ttyB approved these changes

2019-04-23 18:06 UTC, merged

2019-04-29 16:55 UTC, m8ttyB commented
Let's move this to it's own branch called `production`.